use proyecto;

INSERT INTO clubs (club_name) VALUES ('Real Madrid');
INSERT INTO clubs (club_name) VALUES ('Barcelona');
INSERT INTO clubs (club_name) VALUES ('Atletico de Madrid');
INSERT INTO clubs (club_name) VALUES ('Borussia Dortmund');
INSERT INTO clubs (club_name) VALUES ('Liverpool');
INSERT INTO clubs (club_name) VALUES ('Chelsea');
INSERT INTO clubs (club_name) VALUES ('Olympique de Lyon');
INSERT INTO clubs (club_name) VALUES ('Paris Saint Gemain');
INSERT INTO clubs (club_name) VALUES ('Inter');
INSERT INTO clubs (club_name) VALUES ('Milan');
INSERT INTO clubs (club_name) VALUES ('Manchester United');
INSERT INTO clubs (club_name) VALUES ('Niza');
INSERT INTO clubs (club_name) VALUES ('Sevilla');
INSERT INTO clubs (club_name) VALUES ('Leipzig');
INSERT INTO clubs (club_name) VALUES ('Rennes');
INSERT INTO clubs (club_name) VALUES ('Getafe');
INSERT INTO clubs (club_name) VALUES ('Eibar');
INSERT INTO clubs (club_name) VALUES ('Villareal');
