use proyecto;

INSERT INTO clubs (club_name) VALUES ('Real Madrid');
INSERT INTO clubs (club_name) VALUES ('Barcelona');
INSERT INTO clubs (club_name) VALUES ('Atlético de Madrid');
INSERT INTO clubs (club_name) VALUES ('Bayer de Munich');
INSERT INTO clubs (club_name) VALUES ('Borussia Dortmund');
INSERT INTO clubs (club_name) VALUES ('Liverpool');
INSERT INTO clubs (club_name) VALUES ('Chelsea');
INSERT INTO clubs (club_name) VALUES ('Tottenham');
INSERT INTO clubs (club_name) VALUES ('Olympique de Lyon');
INSERT INTO clubs (club_name) VALUES ('Paris Saint Gemain');
INSERT INTO clubs (club_name) VALUES ('Real Sociedad');
INSERT INTO clubs (club_name) VALUES ('Juventus');
INSERT INTO clubs (club_name) VALUES ('Inter');
INSERT INTO clubs (club_name) VALUES ('Milán');
INSERT INTO clubs (club_name) VALUES ('Nápoles');
INSERT INTO clubs (club_name) VALUES ('Boca Juniors');
INSERT INTO clubs (club_name) VALUES ('River Plate');
INSERT INTO clubs (club_name) VALUES ('Flamengo');
INSERT INTO clubs (club_name) VALUES ('Santos');
INSERT INTO clubs (club_name) VALUES ('Palmeiras');