INSERT INTO skills (skill) VALUES ('Reflejos');
INSERT INTO skills (skill) VALUES ('Salida por alto');
INSERT INTO skills (skill) VALUES ('Ambidiestro');
INSERT INTO skills (skill) VALUES ('Regateador');
INSERT INTO skills (skill) VALUES ('Rematador');
INSERT INTO skills (skill) VALUES ('Juego de espaldas');
INSERT INTO skills (skill) VALUES ('Posicionamiento');
INSERT INTO skills (skill) VALUES ('Pase largo');
INSERT INTO skills (skill) VALUES ('Pase corto');
INSERT INTO skills (skill) VALUES ('Visión de juego');
INSERT INTO skills (skill) VALUES ('Buen repliegue');
INSERT INTO skills (skill) VALUES ('Recuperador');
INSERT INTO skills (skill) VALUES ('Buenos controles');
INSERT INTO skills (skill) VALUES ('Gran arrancada');
INSERT INTO skills (skill) VALUES ('Juego aéreo');
INSERT INTO skills (skill) VALUES ('Tiros libres');